- hosts: qa
  become: true
  vars_files:
    - ../group_vars/qa/sar.yml

  tasks:

    - name: Instalar dependencias para descomprimir zip
      ansible.builtin.apt:
        name:
          - unzip
        state: present
        update_cache: true

    - name: Crear directorio base
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin"
        state: directory
        mode: "0755"

    - name: Copiar Dockerfile
      ansible.builtin.copy:
        src: ../admin/Dockerfile
        dest: "{{ sar_base_dir }}/admin/Dockerfile"
        mode: "0644"

    - name: Copiar publish de la app
      ansible.builtin.copy:
        src: ../admin/publish.zip
        dest: "{{ sar_base_dir }}/admin/"
        mode: preserve

    - name: Descomprimir publish.zip
      ansible.builtin.unarchive:
        src: "{{ sar_base_dir }}/admin/publish.zip"
        dest: "{{ sar_base_dir }}/admin/"
        remote_src: true

    - name: Asegurar permisos de publish
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish"
        state: directory
        recurse: true
        mode: "0755"

    - name: Ver uso de Docker
      ansible.builtin.command: docker system df
      register: docker_df
      changed_when: false

    - name: Mostrar uso de Docker
      ansible.builtin.debug:
        var: docker_df.stdout

    - name: Construir imagen Docker
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ sar_base_dir }}/admin"
          dockerfile: Dockerfile
          pull: true

    - name: Mostrar resultado del build
      ansible.builtin.debug:
        var: docker_build_result
        
    - name: Eliminar publish.zip
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish.zip"
        state: absent

    - name: Eliminar carpeta publish descomprimida
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish"
        state: absent

    - name: Crear directorio nginx/ssl
      file:
        path: "{{ sar_base_dir }}/nginx/ssl"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    # - name: Clonar solo la rama y sin blobs
    #   ansible.builtin.command:
    #     cmd: >
    #       git clone --depth 1 --single-branch --branch {{ repo_branch }}
    #       --filter=blob:none --sparse {{ sar_repo_url }} {{ sar_base_dir }}/SAR
    #   args:
    #     creates: "{{ sar_base_dir }}/SAR/.git"

    - name: Clonar / Actualizar repo de SAR
      ansible.builtin.git:
        repo: "{{ sar_repo_url }}"
        dest: "{{ sar_base_dir }}/SAR"
        version: "{{ repo_branch }}"
        depth: 1
        single_branch: true
        force: true
        accept_hostkey: true

    - name: Sincronizar app al servidor
      ansible.posix.synchronize:
        src: ../admin/
        dest: "{{ sar_base_dir }}/admin"
        recursive: true
        delete: false
    
    - name: Activar sparse-checkout para solo el API
      ansible.builtin.command:
        cmd: git sparse-checkout set gql-sep-asuntos-relevantes
        chdir: "{{ sar_base_dir }}/SAR"

    # - name: Copiar PEM al directorio ssl
    #   copy:
    #     src: /home/ubuntu/projects/nginx/ssl/cloudflare-origin.pem
    #     dest: /home/ubuntu/sar/nginx/ssl/cloudflare-origin.pem
    #     remote_src: yes
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: "0644"

    # - name: Copiar KEY al directorio ssl
    #   copy:
    #     src: /home/ubuntu/projects/nginx/ssl/cloudflare-origin.key
    #     dest: /home/ubuntu/sar/nginx/ssl/cloudflare-origin.key
    #     remote_src: yes
    #     owner: "{{ ansible_user }}"
    #     group: "{{ ansible_user }}"
    #     mode: "0600"
    
    - name: Copiar .env
      ansible.builtin.template:
        src: env.j2
        dest: "{{ sar_base_dir }}/.env"
        owner: root
        group: root
        mode: "0600"
    
    - name: Copiar docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.qa.yml.j2
        dest: "{{ sar_base_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "0644"

    - name: Copiar nginx.conf
      ansible.builtin.template:
        src: nginx.qa.conf.j2
        dest: "{{ sar_base_dir }}/nginx/nginx.conf"
        owner: root
        group: root
        mode: "0644"

    - name: Levantar servicios con docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ sar_base_dir }}"
        state: present
        build: always

