- hosts: qa
  become: true
  vars_files:
    - ../group_vars/qa/sar.frontend.yml

  tasks:

    # - name: Instalar dependencias para descomprimir zip
    #   ansible.builtin.apt:
    #     name:
    #       - unzip
    #     state: present
    #     update_cache: true
    - name: Instalar dependencias para descomprimir zip
      ansible.builtin.package:
        name: unzip
        state: present

    - name: Crear directorio base
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin"
        state: directory
        mode: "0755"

    - name: Copiar Dockerfile
      ansible.builtin.copy:
        src: ../admin/Dockerfile
        dest: "{{ sar_base_dir }}/admin/Dockerfile"
        mode: "0644"

    - name: Copiar publish de la app
      ansible.builtin.copy:
        src: ../admin/publish.zip
        # dest: "{{ sar_base_dir }}/admin/"
        dest: "{{ sar_base_dir }}/admin/publish.zip"
        mode: preserve

    - name: Descomprimir publish.zip
      ansible.builtin.unarchive:
        src: "{{ sar_base_dir }}/admin/publish.zip"
        dest: "{{ sar_base_dir }}/admin/"
        remote_src: true

    - name: Asegurar permisos de publish
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish"
        state: directory
        recurse: true
        mode: "0755"

    - name: Ver uso de Docker
      ansible.builtin.command: docker system df
      register: docker_df
      changed_when: false

    - name: Mostrar uso de Docker
      ansible.builtin.debug:
        var: docker_df.stdout

    - name: Construir imagen Docker
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: build
        build:
          path: "{{ sar_base_dir }}/admin"
          dockerfile: Dockerfile
          pull: true
      register: docker_build_result

    - name: Mostrar resultado del build
      ansible.builtin.debug:
        var: docker_build_result
        
    - name: Eliminar publish.zip
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish.zip"
        state: absent

    - name: Eliminar carpeta publish descomprimida
      ansible.builtin.file:
        path: "{{ sar_base_dir }}/admin/publish"
        state: absent

    # - name: Sincronizar app al servidor
    #   ansible.posix.synchronize:
    #     src: ../admin/
    #     dest: "{{ sar_base_dir }}/admin"
    #     recursive: true
    #     delete: false
    
    - name: Copiar .env
      ansible.builtin.template:
        src: frontend.env.j2
        dest: "{{ sar_base_dir }}/.env"
        owner: root
        group: root
        mode: "0600"
    
    - name: Copiar docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.qa.front.yml.j2
        dest: "{{ sar_base_dir }}/docker-compose.yml"
        owner: root
        group: root
        mode: "0644"

    - name: Levantar servicios con docker compose
      community.docker.docker_compose_v2:
        project_src: "{{ sar_base_dir }}"
        state: present
        build: never

